/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Vista.java
 *
 * Created on 02-may-2011, 23:08:10
 */

package sudoku;

/**
 *
 * @author Sergio
 */
public class Vista extends javax.swing.JFrame {

    int[][] puzzle;

    /** Creates new form Vista */
    public Vista() {
        int[][] puzzle5 ={
            {0,0,3, 4,9,0, 0,0,5},
            {0,0,6, 0,0,8, 3,0,0},
            {2,0,0, 0,6,0, 0,0,0},

            {0,4,5, 0,0,6, 0,9,8},
            {0,2,0, 0,0,0, 0,5,0},
            {8,6,0, 9,0,0, 2,4,0},

            {0,0,0, 0,3,0, 0,0,7},
            {0,0,2, 1,0,0, 9,0,0},
            {6,0,0, 0,4,9, 5,0,0}
        };
        initComponents();
        ((Board)tablero).setup(puzzle5);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablero = new Board();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablero.setLayout(new java.awt.GridLayout(9, 9));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablero, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablero, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        int[][] puzzle ={
            {0,6,2, 3,0,0, 9,0,0},
            {0,0,0, 0,8,0, 0,0,7},
            {8,0,0, 0,0,0, 0,0,4},

            {0,0,5, 0,2,0, 0,0,6},
            {0,3,0, 9,4,6, 0,5,0},
            {4,0,0, 0,0,0, 7,0,0},

            {7,0,0, 6,0,0, 0,0,3},
            {5,0,0, 0,3,0, 0,0,0},
            {0,0,3, 0,0,7, 8,9,0}
        };


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel tablero;
    // End of variables declaration//GEN-END:variables

}
